import { DISEASES } from './diseaseDatabase'
import { SNP_METADATA } from './snpMetadata'
import type { Disease } from '@/lib/types'

export type ProfileCategory =
  | 'normal'
  | 'carrier'
  | 'affected'
  | 'combined'
  | 'x_linked'
  | 'edge_case'

export interface TestProfile {
  id: string
  label: string
  description: string
  category: ProfileCategory
  tags: string[]
  expectedMaleStatus?: Record<string, string>   // diseaseId → status
  expectedFemaleStatus?: Record<string, string>
  snpMap: Record<string, string>
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function allNormalBase(): Record<string, string> {
  const map: Record<string, string> = {}
  for (const d of DISEASES) {
    for (const v of d.variants) {
      map[v.rsid] = v.normalAllele + v.normalAllele
    }
  }
  return map
}

function genoCarrier(d: Disease, vIdx = 0): Record<string, string> {
  const v = d.variants[vIdx]
  if (!v) return {}
  return { [v.rsid]: v.normalAllele + v.riskAllele }
}

function genoAffected(d: Disease): Record<string, string> {
  const snps: Record<string, string> = {}
  for (const v of d.variants) {
    snps[v.rsid] = v.riskAllele + v.riskAllele
  }
  return snps
}

function merge(...maps: Record<string, string>[]): Record<string, string> {
  return Object.assign({}, ...maps)
}

function dis(id: string): Disease {
  return DISEASES.find(d => d.id === id)!
}

// Generate 23andMe-format TSV content for a profile
export function profileToTSV(profile: TestProfile): string {
  const lines = [
    '# This data file was generated by DNAMatch Test Mode',
    `# Profile: ${profile.label}`,
    `# Description: ${profile.description}`,
    `# Category: ${profile.category}`,
    '# rsid\tchromosome\tposition\tgenotype',
  ]
  for (const [rsid, genotype] of Object.entries(profile.snpMap)) {
    const meta = SNP_METADATA[rsid]
    if (meta) {
      lines.push(`${rsid}\t${meta.chromosome}\t${meta.position}\t${genotype}`)
    }
  }
  return lines.join('\n')
}

// ─── Profile Generation ───────────────────────────────────────────────────────

function buildProfiles(): TestProfile[] {
  const profiles: TestProfile[] = []
  const base = allNormalBase()

  // ── Category A: Single disease – Normal (22) ────────────────────────────────
  for (const d of DISEASES) {
    profiles.push({
      id: `${d.id}_normal`,
      label: `${d.name} — Normal`,
      description: `All variants for ${d.name} (${d.gene}) show normal / wild-type genotype.`,
      category: 'normal',
      tags: [d.name, d.gene, 'normal'],
      snpMap: { ...base },
    })
  }

  // ── Category B: Single disease – Carrier (22) ──────────────────────────────
  for (const d of DISEASES) {
    const isXLinked = d.inheritance === 'x_linked_recessive' || d.inheritance === 'x_linked_dominant'
    profiles.push({
      id: `${d.id}_carrier`,
      label: `${d.name} — Carrier`,
      description: isXLinked
        ? `Heterozygous (carrier) for ${d.name}. Relevant for females; males would be affected.`
        : `Heterozygous carrier for ${d.name} (${d.gene}). One copy of the risk allele.`,
      category: 'carrier',
      tags: [d.name, d.gene, 'carrier'],
      snpMap: merge(base, genoCarrier(d)),
    })
  }

  // ── Category C: Single disease – Affected (22) ─────────────────────────────
  for (const d of DISEASES) {
    profiles.push({
      id: `${d.id}_affected`,
      label: `${d.name} — Affected`,
      description: `Homozygous / hemizygous risk genotype for ${d.name} (${d.gene}). Two copies of the pathogenic allele.`,
      category: 'affected',
      tags: [d.name, d.gene, 'affected'],
      snpMap: merge(base, genoAffected(d)),
    })
  }

  // ── Category D: Multi-disease Combined (20) ─────────────────────────────────
  const cf   = dis('cystic-fibrosis')
  const sc   = dis('sickle-cell-anemia')
  const bt   = dis('beta-thalassemia')
  const ts   = dis('tay-sachs')
  const pku  = dis('pku')
  const gc   = dis('gaucher')
  const sma  = dis('sma')
  const wd   = dis('wilsons')
  const hfe  = dis('hemochromatosis')
  const htn  = dis('huntingtons')
  const fh   = dis('familial-hypercholesterolemia')
  const b1   = dis('brca1')
  const b2   = dis('brca2')
  const fvl  = dis('factor-v-leiden')
  const mthf = dis('mthfr')
  const pt   = dis('prothrombin-g20210a')
  const haem = dis('hemophilia-a')
  const haemb= dis('hemophilia-b')
  const dmd  = dis('dmd')
  const cb   = dis('color-blindness')
  const fx   = dis('fragile-x')
  const marfan = dis('marfan')

  const combined: Omit<TestProfile, 'snpMap'>[] = [
    { id: 'combo_ashkenazi_panel', label: 'Ashkenazi Jewish Panel — Carrier', description: 'Carrier for CF, Tay-Sachs, and Gaucher Disease — the core Ashkenazi carrier screen.', category: 'combined', tags: ['CF', 'Tay-Sachs', 'Gaucher', 'Ashkenazi', 'carrier'] },
    { id: 'combo_mediterranean_panel', label: 'Mediterranean Panel — Carrier', description: 'Carrier for Sickle Cell Anemia and Beta-Thalassemia — common in Mediterranean populations.', category: 'combined', tags: ['Sickle Cell', 'Beta-Thal', 'Mediterranean', 'carrier'] },
    { id: 'combo_cf_sma_carrier', label: 'CF + SMA — Carrier', description: 'Carrier for both Cystic Fibrosis and Spinal Muscular Atrophy.', category: 'combined', tags: ['CF', 'SMA', 'carrier'] },
    { id: 'combo_brca_carrier', label: 'BRCA1 + BRCA2 — Carrier', description: 'Carrier for both BRCA1 (185delAG) and BRCA2 (6174delT) founder mutations.', category: 'combined', tags: ['BRCA1', 'BRCA2', 'cancer', 'carrier'] },
    { id: 'combo_cardiac_risk', label: 'Cardiac Risk — Factor V + Prothrombin', description: 'Carrier for Factor V Leiden and Prothrombin G20210A — elevated clotting risk.', category: 'combined', tags: ['Factor V', 'Prothrombin', 'thrombosis', 'carrier'] },
    { id: 'combo_mthfr_compound', label: 'MTHFR Compound Heterozygous', description: 'Heterozygous for both MTHFR C677T and A1298C — the clinically relevant compound form.', category: 'combined', tags: ['MTHFR', 'compound het', 'cardiovascular'] },
    { id: 'combo_hfe_compound', label: 'HFE Compound Heterozygous (C282Y + H63D)', description: 'One copy of C282Y and one copy of H63D in HFE — compound heterozygous hemochromatosis.', category: 'combined', tags: ['Hemochromatosis', 'HFE', 'compound het'] },
    { id: 'combo_cf_compound_het', label: 'CF Compound Heterozygous (ΔF508 + W1282X)', description: 'Carrier of two different CF mutations (ΔF508 on one chromosome, W1282X on the other).', category: 'combined', tags: ['CF', 'compound het'] },
    { id: 'combo_pku_sma_wd', label: 'PKU + SMA + Wilson\'s — Carrier', description: 'Carrier for PKU, SMA, and Wilson\'s Disease simultaneously.', category: 'combined', tags: ['PKU', 'SMA', "Wilson's", 'carrier'] },
    { id: 'combo_four_ar_carrier', label: 'Four AR Diseases — Carrier', description: 'Carrier for CF, Sickle Cell, Tay-Sachs, and PKU — tests scoring with multiple AR risks.', category: 'combined', tags: ['CF', 'Sickle Cell', 'Tay-Sachs', 'PKU', 'carrier'] },
    { id: 'combo_six_ar_carrier', label: 'Six AR Diseases — Carrier', description: 'Carrier for six autosomal recessive diseases — tests moderate compatibility score.', category: 'combined', tags: ['multi-carrier', 'autosomal recessive'] },
    { id: 'combo_dominant_multiple', label: 'Multiple Dominant Risk Variants', description: 'Carrier for Huntington\'s proxy, BRCA1, FH, and Factor V Leiden.', category: 'combined', tags: ['dominant', 'BRCA1', 'FH', 'Huntington'] },
    { id: 'combo_cancer_predisposition', label: 'Cancer Predisposition Profile', description: 'BRCA1 + BRCA2 carrier with FH — elevated cancer and cardiovascular inherited risk.', category: 'combined', tags: ['BRCA1', 'BRCA2', 'FH', 'cancer'] },
    { id: 'combo_metabolic_carrier', label: 'Metabolic Disease Carrier', description: 'Carrier for PKU, Gaucher Disease, and Wilson\'s Disease.', category: 'combined', tags: ['PKU', 'Gaucher', "Wilson's", 'metabolic'] },
    { id: 'combo_cardiovascular_full', label: 'Full Cardiovascular Risk Profile', description: 'Factor V Leiden + Prothrombin + FH + MTHFR compound het.', category: 'combined', tags: ['cardiovascular', 'thrombosis', 'FH', 'MTHFR'] },
    { id: 'combo_high_risk_ar', label: 'High Risk — Two Severe AR Carriers', description: 'Carrier for CF (lethal severity) and Tay-Sachs (lethal severity).', category: 'combined', tags: ['CF', 'Tay-Sachs', 'lethal', 'high risk'] },
    { id: 'combo_all_ar_carrier', label: 'All AR Diseases — Carrier', description: 'Carrier for every autosomal recessive disease in the database.', category: 'combined', tags: ['all AR', 'max carrier'] },
    { id: 'combo_brca_fvl', label: 'BRCA1 + Factor V Leiden — Carrier', description: 'BRCA1 carrier combined with Factor V Leiden — elevated cancer and clotting risk.', category: 'combined', tags: ['BRCA1', 'Factor V', 'cancer', 'clotting'] },
    { id: 'combo_sickle_gaucher', label: 'Sickle Cell + Gaucher — Carrier', description: 'Carrier for both Sickle Cell Anemia and Gaucher Disease.', category: 'combined', tags: ['Sickle Cell', 'Gaucher', 'carrier'] },
    { id: 'combo_marfan_brca', label: 'Marfan + BRCA2 — Carrier', description: 'Carrier for Marfan Syndrome and BRCA2 — two dominant conditions.', category: 'combined', tags: ['Marfan', 'BRCA2', 'dominant'] },
  ]

  const combinedSNPs: Record<string, Record<string, string>> = {
    combo_ashkenazi_panel:    merge(genoCarrier(cf), genoCarrier(ts), genoCarrier(gc)),
    combo_mediterranean_panel: merge(genoCarrier(sc), genoCarrier(bt)),
    combo_cf_sma_carrier:     merge(genoCarrier(cf), genoCarrier(sma)),
    combo_brca_carrier:       merge(genoCarrier(b1), genoCarrier(b2)),
    combo_cardiac_risk:       merge(genoCarrier(fvl), genoCarrier(pt)),
    combo_mthfr_compound:     merge(genoCarrier(mthf, 0), genoCarrier(mthf, 1)),
    combo_hfe_compound:       merge(genoCarrier(hfe, 0), genoCarrier(hfe, 1)),
    combo_cf_compound_het:    merge(genoCarrier(cf, 0), genoCarrier(cf, 1)),
    combo_pku_sma_wd:         merge(genoCarrier(pku), genoCarrier(sma), genoCarrier(wd)),
    combo_four_ar_carrier:    merge(genoCarrier(cf), genoCarrier(sc), genoCarrier(ts), genoCarrier(pku)),
    combo_six_ar_carrier:     merge(genoCarrier(cf), genoCarrier(sc), genoCarrier(ts), genoCarrier(pku), genoCarrier(gc), genoCarrier(sma)),
    combo_dominant_multiple:  merge(genoCarrier(htn), genoCarrier(b1), genoCarrier(fh), genoCarrier(fvl)),
    combo_cancer_predisposition: merge(genoCarrier(b1), genoCarrier(b2), genoCarrier(fh)),
    combo_metabolic_carrier:  merge(genoCarrier(pku), genoCarrier(gc), genoCarrier(wd)),
    combo_cardiovascular_full: merge(genoCarrier(fvl), genoCarrier(pt), genoCarrier(fh), genoCarrier(mthf, 0), genoCarrier(mthf, 1)),
    combo_high_risk_ar:       merge(genoCarrier(cf), genoCarrier(ts)),
    combo_all_ar_carrier:     merge(genoCarrier(cf), genoCarrier(sc), genoCarrier(bt), genoCarrier(ts), genoCarrier(pku), genoCarrier(gc), genoCarrier(sma), genoCarrier(wd), genoCarrier(hfe)),
    combo_brca_fvl:           merge(genoCarrier(b1), genoCarrier(fvl)),
    combo_sickle_gaucher:     merge(genoCarrier(sc), genoCarrier(gc)),
    combo_marfan_brca:        merge(genoCarrier(marfan), genoCarrier(b2)),
  }

  for (const def of combined) {
    profiles.push({ ...def, snpMap: merge(base, combinedSNPs[def.id] ?? {}) })
  }

  // ── Category E: X-Linked Specific (12) ─────────────────────────────────────
  const xLinkedDiseases = [haem, haemb, dmd, cb]
  for (const d of xLinkedDiseases) {
    // Affected male (hemizygous — represented as homozygous risk)
    profiles.push({
      id: `${d.id}_male_affected`,
      label: `${d.name} — Affected Male`,
      description: `Male with hemizygous pathogenic allele for ${d.name}. Single X copy is affected.`,
      category: 'x_linked',
      tags: [d.name, 'X-linked', 'male', 'affected'],
      snpMap: merge(base, genoAffected(d)),
    })
    // Normal male
    profiles.push({
      id: `${d.id}_male_normal`,
      label: `${d.name} — Normal Male`,
      description: `Male with normal X genotype for ${d.name}.`,
      category: 'x_linked',
      tags: [d.name, 'X-linked', 'male', 'normal'],
      snpMap: { ...base },
    })
    // Carrier female
    profiles.push({
      id: `${d.id}_female_carrier`,
      label: `${d.name} — Carrier Female`,
      description: `Female carrier for ${d.name}. Heterozygous X — typically unaffected but can pass to sons.`,
      category: 'x_linked',
      tags: [d.name, 'X-linked', 'female', 'carrier'],
      snpMap: merge(base, genoCarrier(d)),
    })
  }

  // ── Category F: Special / Edge Cases (20) ──────────────────────────────────
  const edgeCases: TestProfile[] = [
    {
      id: 'special_all_normal',
      label: 'All Diseases — Normal',
      description: 'Wild-type for every disease in the database. Expected score: 100 (Excellent).',
      category: 'edge_case',
      tags: ['baseline', 'all normal', 'score 100'],
      snpMap: { ...base },
    },
    {
      id: 'special_all_ar_affected',
      label: 'All AR Diseases — Affected',
      description: 'Homozygous risk at all autosomal recessive diseases. Extreme test case.',
      category: 'edge_case',
      tags: ['extreme', 'all affected', 'AR'],
      snpMap: merge(base, genoAffected(cf), genoAffected(sc), genoAffected(bt), genoAffected(ts), genoAffected(pku), genoAffected(gc), genoAffected(sma), genoAffected(wd), genoAffected(hfe)),
    },
    {
      id: 'special_all_dominant_affected',
      label: 'All Dominant Conditions — Carrier',
      description: 'Carrier for all autosomal dominant conditions in the database.',
      category: 'edge_case',
      tags: ['dominant', 'all affected'],
      snpMap: merge(base, genoCarrier(htn), genoCarrier(fh), genoCarrier(b1), genoCarrier(b2), genoCarrier(fvl), genoCarrier(marfan)),
    },
    {
      id: 'special_x_female_all_carrier',
      label: 'All X-Linked — Carrier Female',
      description: 'Carrier female for all X-linked diseases in the database.',
      category: 'x_linked',
      tags: ['X-linked', 'female', 'carrier', 'all'],
      snpMap: merge(base, genoCarrier(haem), genoCarrier(haemb), genoCarrier(dmd), genoCarrier(cb), genoCarrier(fx)),
    },
    {
      id: 'special_x_male_all_affected',
      label: 'All X-Linked — Affected Male',
      description: 'Affected male for all X-linked recessive diseases.',
      category: 'x_linked',
      tags: ['X-linked', 'male', 'affected', 'all'],
      snpMap: merge(base, genoAffected(haem), genoAffected(haemb), genoAffected(dmd), genoAffected(cb)),
    },
    {
      id: 'special_high_compatibility',
      label: 'High Compatibility Pair Baseline',
      description: 'Ideal baseline profile: all normal. Use as both Father and Mother for a 100/100 score.',
      category: 'edge_case',
      tags: ['baseline', 'high compatibility'],
      snpMap: { ...base },
    },
    {
      id: 'special_low_compatibility',
      label: 'Low Compatibility — Matched Carriers',
      description: 'Carrier for CF, Tay-Sachs, Sickle Cell, and SMA. Use as both Father AND Mother to simulate matched carriers (25% affected per disease).',
      category: 'edge_case',
      tags: ['low compatibility', 'matched carriers', 'scoring test'],
      snpMap: merge(base, genoCarrier(cf), genoCarrier(ts), genoCarrier(sc), genoCarrier(sma)),
    },
    {
      id: 'special_partial_5snps',
      label: 'Partial Data — 5 SNPs Only',
      description: 'Only 5 disease-relevant SNPs present. Tests Unknown status handling and partial file behavior.',
      category: 'edge_case',
      tags: ['partial data', 'edge case', 'unknown status'],
      snpMap: {
        'rs1800562': 'GG', // HFE C282Y normal
        'rs1799945': 'CC', // HFE H63D normal
        'rs6025':    'GG', // Factor V Leiden normal
        'rs1801133': 'CT', // MTHFR C677T carrier
        'rs1801131': 'AA', // MTHFR A1298C normal
      },
    },
    {
      id: 'special_partial_brca_only',
      label: 'Partial Data — BRCA Only',
      description: 'Only BRCA1 and BRCA2 variants present. All other diseases will show Unknown.',
      category: 'edge_case',
      tags: ['partial data', 'BRCA only'],
      snpMap: merge(genoCarrier(b1), genoCarrier(b2)),
    },
    {
      id: 'special_mthfr_homozygous_tt',
      label: 'MTHFR Homozygous TT (C677T)',
      description: 'Homozygous for MTHFR C677T thermolabile variant. Mildly elevated homocysteine risk.',
      category: 'edge_case',
      tags: ['MTHFR', 'homozygous', 'C677T'],
      snpMap: merge(base, genoAffected(mthf)),
    },
    {
      id: 'special_hfe_c282y_homozygous',
      label: 'HFE C282Y Homozygous (Classical HH)',
      description: 'Homozygous for HFE C282Y — classical hereditary hemochromatosis.',
      category: 'edge_case',
      tags: ['HFE', 'hemochromatosis', 'C282Y', 'homozygous'],
      snpMap: merge(base, { 'rs1800562': 'AA', 'rs1799945': 'CC' }),
    },
    {
      id: 'special_sickle_beta_thal',
      label: 'Sickle Cell + Beta-Thal — Double HBB Carrier',
      description: 'Carrier for both HBB mutations (sickle cell AND beta-thal). Both affect the same gene.',
      category: 'edge_case',
      tags: ['HBB', 'Sickle Cell', 'Beta-Thal', 'compound'],
      snpMap: merge(base, genoCarrier(sc), genoCarrier(bt)),
    },
    {
      id: 'special_fragile_x_carrier',
      label: 'Fragile X — Premutation Carrier',
      description: 'Carrier for Fragile X syndrome proxy SNP. Note: definitive diagnosis requires repeat testing.',
      category: 'x_linked',
      tags: ['Fragile X', 'X-linked', 'carrier'],
      snpMap: merge(base, genoCarrier(fx)),
    },
    {
      id: 'special_huntingtons_proxy',
      label: 'Huntington\'s — Risk Proxy Present',
      description: 'Carries the HTT proxy risk marker. Note: this is NOT diagnostic — CAG repeat testing is required.',
      category: 'edge_case',
      tags: ["Huntington's", 'proxy', 'dominant'],
      snpMap: merge(base, genoCarrier(htn)),
    },
    {
      id: 'special_high_dominant_risk',
      label: 'High Dominant Risk — Multiple Serious Conditions',
      description: "BRCA1 + BRCA2 + Huntington's proxy + FH carrier. Tests scoring of multiple dominant conditions.",
      category: 'edge_case',
      tags: ['BRCA', "Huntington's", 'FH', 'dominant', 'high risk'],
      snpMap: merge(base, genoCarrier(b1), genoCarrier(b2), genoCarrier(htn), genoCarrier(fh)),
    },
    {
      id: 'special_all_eight_ar_carrier',
      label: '8 AR Diseases — Carrier',
      description: 'Carrier for 8 autosomal recessive diseases. Tests multi-carrier detection and score calculation.',
      category: 'edge_case',
      tags: ['multi-carrier', 'AR', 'scoring'],
      snpMap: merge(base, genoCarrier(cf), genoCarrier(sc), genoCarrier(bt), genoCarrier(ts), genoCarrier(pku), genoCarrier(gc), genoCarrier(wd), genoCarrier(hfe)),
    },
    {
      id: 'special_empty_no_variants',
      label: 'Empty — No Relevant Variants',
      description: 'No disease-relevant SNPs present. All results will show Unknown status. Tests graceful degradation.',
      category: 'edge_case',
      tags: ['empty', 'no data', 'unknown'],
      snpMap: {},
    },
    {
      id: 'special_prothrombin_homozygous',
      label: 'Prothrombin G20210A — Homozygous',
      description: 'Homozygous for prothrombin G20210A mutation — significantly elevated clotting risk.',
      category: 'edge_case',
      tags: ['Prothrombin', 'thrombosis', 'homozygous'],
      snpMap: merge(base, genoAffected(pt)),
    },
    {
      id: 'special_cf_affected_rest_normal',
      label: 'CF Affected — Everything Else Normal',
      description: 'Affected for Cystic Fibrosis only. Tests that one severe disease lowers score appropriately.',
      category: 'edge_case',
      tags: ['CF', 'affected', 'scoring'],
      snpMap: merge(base, genoAffected(cf)),
    },
    {
      id: 'special_combined_maximum_risk',
      label: 'Maximum Risk — Carriers Across All Groups',
      description: 'Carrier for CF, Tay-Sachs (AR) + BRCA1 (dominant) + Hemophilia A (X-linked). Tests all inheritance types.',
      category: 'edge_case',
      tags: ['all inheritance types', 'maximum risk', 'test'],
      snpMap: merge(base, genoCarrier(cf), genoCarrier(ts), genoCarrier(b1), genoCarrier(haem)),
    },
  ]

  profiles.push(...edgeCases)

  return profiles
}

export const TEST_PROFILES: TestProfile[] = buildProfiles()

// Grouped for the UI selector
export const PROFILE_GROUPS: { label: string; category: ProfileCategory; profiles: TestProfile[] }[] = [
  { label: 'Normal (no risk)', category: 'normal', profiles: TEST_PROFILES.filter(p => p.category === 'normal') },
  { label: 'Carriers',         category: 'carrier', profiles: TEST_PROFILES.filter(p => p.category === 'carrier') },
  { label: 'Affected',         category: 'affected', profiles: TEST_PROFILES.filter(p => p.category === 'affected') },
  { label: 'Combined / Multi', category: 'combined', profiles: TEST_PROFILES.filter(p => p.category === 'combined') },
  { label: 'X-Linked',         category: 'x_linked', profiles: TEST_PROFILES.filter(p => p.category === 'x_linked') },
  { label: 'Edge Cases',       category: 'edge_case', profiles: TEST_PROFILES.filter(p => p.category === 'edge_case') },
]
